#####################################################################
# Campaign options:
#
# id: used for identifying campaign, placement of results
#####################################################################
campaign:
    id: client_demo
#####################################################################
# Fuzz target options:
#
# target: 
# intent: a container for the necessary components to construct
# an intent
#####################################################################
target:
    intent:
        action: android.intent.action.VIEW
        component: com.android.browser/.BrowserActivity
        categories:
            - android.intent.category.BROWSABLE
        mime_type: text/html
#####################################################################
# Directories used by BFF for Android:
#
# directories:
# seedfile_dir: the directory containing the seedfiles
# apk_dir: the directory containing any APKs to install
# working_dir:
# results_dir: the directory in which to output results
# seedfile_cache: the location of the seedfile cache
#####################################################################
directories:
    seedfile_dir: seedfiles
    apk_dir: apks
    working_dir: /tmp
    results_dir: results
    seedfile_cache: '~/seedfile_cache'
#####################################################################
# Fuzz run options
#
# first_iteration: The iteration number to begin with. Defaults to zero
#                  if not present.
# last_iteration: The iteration when a fuzzing campaign ends. If set
#                 to zero or not present, the campaign will continue 
#                 until the fuzzer runs out of things to do.
# minimize: Create a file that is minimally-different than the seed 
#           file, yet crashes with the same hash
# minimizer_timeout: The maximum amount of time that FOE will spend on
#                    a minimization run before giving up
# keep_unique_faddr: Consider the Exception Faulting Address value as
#                    part of the crash hash
# keep_all_duplicates: Keep all duplicate crashing cases
#####################################################################
runoptions:
    first_iteration: 0
    last_iteration: 1
    # minimize: true
    # minimizer_timeout: 3600
    # keep_unique_faddr: False
    # keep_all_duplicates: False
#####################################################################
# Fuzzer options
#
# fuzzer:
# bytemut: replace bytes with random values
#####################################################################
fuzzer:
    fuzzer: bytemut
#####################################################################
# Runner options
#
# runner:
# runtimeout: TODO
#####################################################################
runner:
    runtimeout: 2
#####################################################################
# Database options:
#
# db:
# host: the host running the database service
# port: the port on which the database service is listening
# username: the username by which to authenticate
# password: the password by which to authenticate
# dbname: the database to store data within
#####################################################################
db: 
    host: localhost
    port: 5984
    username: couchadmin
    password: couchpassword
    dbname: bff
#####################################################################
# Emulator options:
#
# number: the number of emulators that should run concurrently
# sdk_home: the location of the android SDK directories
# avd_home: the directory for android virtual devices
# tombstone_timeout: the number of attempts to collect a tombstone
# after an intent has been issued
# orphan_check_interval: the frequency to check if an emulator is
# orphaned
#####################################################################
emulator:
    number: 1
    sdk_home: ~/android-sdk
    avd_home: ~/.android/avd
    avd_name: gold_4.1.2 
    clone: true
    tombstone_timeout: 5
    orphan_check_interval: 5
    timers:
        # how long to wait for an emulator to be deleted before throwing an error
        kill_timeout: 120
        # how long to wait for an emulator to write its handle to a file
        handle_file_timeout: 300
        # how long to wait for a handle when booting an avd
        handle_timeout: 300
        # how long to wait for the sdcard to mount after the devices is ready
        sdcard_timeout: 600
        # time to nap between checking for device in device list
        device_retry: 1